In [2]:
import numpy as np

## np.asarray vs np.array

Convert the input to an array.

In [12]:
a=[1,2]
np_a = np.array([1, 2])


np_b=np.asarray(np_a) #it does not creates copy if already a numpy array
print(np.shares_memory(np_b,np_a))

b = np.asarray(a)  
print(np.shares_memory(a, b))

c=np.array(a) #always creates a copy 
print(np.shares_memory(a,c)) 


True
False
False


## np.random


### choice

In [7]:
a=100 #instead of providing the array we are giving a number then it will consider an array [0,N)
np.random.choice(a,10,replace=False) #replace=True(default) means it will keep the sample back in the set after taking sampling

array([43, 12, 50, 11, 75, 67, 54,  2, 56, 55])

### randint


In [3]:
i=np.random.randint(0,4)  #[0,4)
print(i)

3


## reshape


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
newarr = arr.reshape(4, 3) #4 rows with 3 elements in each
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1) #converting to 1d

print(newarr)

[1 2 3 4 5 6]


In [ ]:
# axis=0 (refers to the vertical axis )
# Operations along axis=0 are applied down each column.
# For example, if you sum along axis=0, you get the sum of each column.

# axis=1 refers to the horizontal axis
# Operations along axis=1 are applied across each row.

# where

In [2]:
import numpy as np

arr=np.array([10,5,23,1,31])

result=np.where(arr>20)

print(result)

(array([2, 4]),)


## np.bincount
for a list gives the count of each number such that the count = index of the returned list

In [3]:
import numpy as np
a=[1,3,5,0,1,2,2,2]
print(np.bincount(a))

[1 2 3 1 0 1]


## np.unique
returns the list of unique value in the given list

In [5]:
print(np.unique(a))

[0 1 2 3 5]


## Masking

In [8]:
left_mask=np.array([True,False,True])
data=np.array([[0,1],[1,1],[0,0]])

print(data[left_mask])

[[0 1]
 [0 0]]


## np.all()

numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.

In [10]:
print(np.all(left_mask))

m2=np.array([True,True,True])

print(np.all(m2))

False
True
