In [2]:
import numpy as np

## np.asarray vs np.array

Convert the input to an array.

In [12]:
a=[1,2]
np_a = np.array([1, 2])


np_b=np.asarray(np_a) #it does not creates copy if already a numpy array
print(np.shares_memory(np_b,np_a))

b = np.asarray(a)  
print(np.shares_memory(a, b))

c=np.array(a) #always creates a copy 
print(np.shares_memory(a,c)) 


True
False
False


## np.random


### choice

In [7]:
a=100 #instead of providing the array we are giving a number then it will consider an array [0,N)
np.random.choice(a,10,replace=False) #replace=True(default) means it will keep the sample back in the set after taking sampling

array([43, 12, 50, 11, 75, 67, 54,  2, 56, 55])

### randint


In [3]:
i=np.random.randint(0,4)  #[0,4)
print(i)

3


## reshape


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
newarr = arr.reshape(4, 3) #4 rows with 3 elements in each
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1) #converting to 1d

print(newarr)

[1 2 3 4 5 6]


In [ ]:
# axis=0 (refers to the vertical axis )
# Operations along axis=0 are applied down each column.
# For example, if you sum along axis=0, you get the sum of each column.

# axis=1 refers to the horizontal axis
# Operations along axis=1 are applied across each row.