In [ ]:
import torch

## Tensor

All deep learning is based on the computation of tensor, which are mathematical objects that describe linear relationships between sets of multidimensional data. They are a generalization of scalars, vectors, and matrices, which are all types of tensor

3 things define the tensor:
- Rank: tensor's number of axis
- Shape: number of dimension along each axis (number of rows and columns in rank 2 tensor)
- Data type

In [35]:
data_1=[1,2,3,4]

V=torch.tensor(data_1)
print(V)

T_data = [[[1., 2.], [3., 4.]], 
          [[5., 6.], [7., 8.]]] 
T = torch.tensor(T_data) 
print(T)

tensor([1, 2, 3, 4])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


## Chunk

In [31]:
x=torch.arange(11).chunk(6)
print(x)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]), tensor([10]))


## Broadcast

In [30]:
# used to make the dimension of both tensor same on the condition of having  
x=torch.arange(4).view(2,2)
y=torch.arange(2).view(1,2)

print(x)
print(y)

a,b=torch.broadcast_tensors(x,y)

print("After broadcasting")

print(a)
print(b)




tensor([[0, 1],
        [2, 3]])
tensor([[0, 1]])
After broadcasting
tensor([[0, 1],
        [2, 3]])
tensor([[0, 1],
        [0, 1]])


## Interpolate

- Down/up samples the input.
- Tensor interpolated to either the given size or the given scale_factor

In [3]:
import torch
import torch.nn as nn

image=torch.Tensor(512,512)
interpolated_img=torch.nn.functional.interpolate(image.unsqueeze(0).unsqueeze(0).float(),size=(256,256),mode='nearest')
print(interpolated_img.shape)



torch.Size([1, 1, 256, 256])


## Numel
returns the total number of elements in the input tensor

In [2]:
import torch
a = torch.zeros(4,4)
print(torch.numel(a))

b=torch.randn(1,2,3,4,5)
print(torch.numel(b))

16
120


## Get the any random sample from Dataloader

In [ ]:
dataset=dataloader.dataset

random_index=int(np.random.random()*len(dataset))
single_example=dataset[random_index]

## ToTransform
Convert PIL Image or ndarray to tensor and scale them 
Detail: Converts PIL image or numpy.ndarray(H,W,C) in range [0,255] to a torch.FloatTensor of shape (C,H,W) in the range [0.0,1.0] 

# LinSpace

In [1]:
import torch

values=torch.linspace(0.0001,0.02,100)
print(values)

tensor([1.0000e-04, 3.0101e-04, 5.0202e-04, 7.0303e-04, 9.0404e-04, 1.1051e-03,
        1.3061e-03, 1.5071e-03, 1.7081e-03, 1.9091e-03, 2.1101e-03, 2.3111e-03,
        2.5121e-03, 2.7131e-03, 2.9141e-03, 3.1152e-03, 3.3162e-03, 3.5172e-03,
        3.7182e-03, 3.9192e-03, 4.1202e-03, 4.3212e-03, 4.5222e-03, 4.7232e-03,
        4.9242e-03, 5.1253e-03, 5.3263e-03, 5.5273e-03, 5.7283e-03, 5.9293e-03,
        6.1303e-03, 6.3313e-03, 6.5323e-03, 6.7333e-03, 6.9343e-03, 7.1354e-03,
        7.3364e-03, 7.5374e-03, 7.7384e-03, 7.9394e-03, 8.1404e-03, 8.3414e-03,
        8.5424e-03, 8.7434e-03, 8.9444e-03, 9.1455e-03, 9.3465e-03, 9.5475e-03,
        9.7485e-03, 9.9495e-03, 1.0151e-02, 1.0352e-02, 1.0553e-02, 1.0754e-02,
        1.0955e-02, 1.1156e-02, 1.1357e-02, 1.1558e-02, 1.1759e-02, 1.1960e-02,
        1.2161e-02, 1.2362e-02, 1.2563e-02, 1.2764e-02, 1.2965e-02, 1.3166e-02,
        1.3367e-02, 1.3568e-02, 1.3769e-02, 1.3970e-02, 1.4171e-02, 1.4372e-02,
        1.4573e-02, 1.4774e-02, 1.4975e-

# CumProd

In [2]:
cum_prod=torch.cumprod(values,dim=0)
print(cum_prod)

tensor([1.0000e-04, 3.0101e-08, 1.5111e-11, 1.0624e-14, 9.6043e-18, 1.0613e-20,
        1.3861e-23, 2.0890e-26, 3.5682e-29, 6.8121e-32, 1.4374e-34, 3.3220e-37,
        8.3453e-40, 2.2645e-42, 7.0065e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+

# nn.Linear
nn.Linear is a fully connected (dense) layer that applies a learnable linear transformation to input vectors.

In [7]:
linear_layer = nn.Linear(in_features=4, out_features=2)  # 4D input → 2D output

input_vector = torch.randn(3, 4)  # 3 samples, each with 4 features
output_vector = linear_layer(input_vector)

print(output_vector.shape)  # Output: (3, 2) → 3 samples, each mapped to 2D

torch.Size([3, 2])


## nn.Embedding

nn.Embedding is a lookup table for storing and retrieving fixed-size vector representations of discrete entities

In [6]:
import torch
import torch.nn as nn

embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=4)

input_indices = torch.tensor([1, 3, 7])  # Each number corresponds to a row in the embedding table

output_vectors = embedding_layer(input_indices)

print(output_vectors.shape)  # Output: (3, 4) → 3 indices mapped to 4D vectors
print(output_vectors)

torch.Size([3, 4])
tensor([[-0.1559, -0.9301, -0.2506,  1.7809],
        [-0.9165,  1.7546,  1.0814,  0.9636],
        [-0.2993, -1.3693,  1.8700, -1.3098]], grad_fn=<EmbeddingBackward0>)
