In [ ]:
import torch

## Tensor

All deep learning is based on the computation of tensor, which are mathematical objects that describe linear relationships between sets of multidimensional data. They are a generalization of scalars, vectors, and matrices, which are all types of tensor

3 things define the tensor:
- Rank: tensor's number of axis
- Shape: number of dimension along each axis (number of rows and columns in rank 2 tensor)
- Data type

In [35]:
data_1=[1,2,3,4]

V=torch.tensor(data_1)
print(V)

T_data = [[[1., 2.], [3., 4.]], 
          [[5., 6.], [7., 8.]]] 
T = torch.tensor(T_data) 
print(T)

tensor([1, 2, 3, 4])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


## Chunk

In [31]:
x=torch.arange(11).chunk(6)
print(x)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]), tensor([10]))


## Broadcast

In [30]:
# used to make the dimension of both tensor same on the condition of having  
x=torch.arange(4).view(2,2)
y=torch.arange(2).view(1,2)

print(x)
print(y)

a,b=torch.broadcast_tensors(x,y)

print("After broadcasting")

print(a)
print(b)




tensor([[0, 1],
        [2, 3]])
tensor([[0, 1]])
After broadcasting
tensor([[0, 1],
        [2, 3]])
tensor([[0, 1],
        [0, 1]])
