In [ ]:
import torch

## Tensor

All deep learning is based on the computation of tensor, which are mathematical objects that describe linear relationships between sets of multidimensional data. They are a generalization of scalars, vectors, and matrices, which are all types of tensor

3 things define the tensor:
- Rank: tensor's number of axis
- Shape: number of dimension along each axis (number of rows and columns in rank 2 tensor)
- Data type

In [35]:
data_1=[1,2,3,4]

V=torch.tensor(data_1)
print(V)

T_data = [[[1., 2.], [3., 4.]], 
          [[5., 6.], [7., 8.]]] 
T = torch.tensor(T_data) 
print(T)

tensor([1, 2, 3, 4])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


## Chunk

In [31]:
x=torch.arange(11).chunk(6)
print(x)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]), tensor([10]))


## Broadcast

In [30]:
# used to make the dimension of both tensor same on the condition of having  
x=torch.arange(4).view(2,2)
y=torch.arange(2).view(1,2)

print(x)
print(y)

a,b=torch.broadcast_tensors(x,y)

print("After broadcasting")

print(a)
print(b)




tensor([[0, 1],
        [2, 3]])
tensor([[0, 1]])
After broadcasting
tensor([[0, 1],
        [2, 3]])
tensor([[0, 1],
        [0, 1]])


## Interpolate

- Down/up samples the input.
- Tensor interpolated to either the given size or the given scale_factor

In [3]:
import torch
import torch.nn as nn

image=torch.Tensor(512,512)
interpolated_img=torch.nn.functional.interpolate(image.unsqueeze(0).unsqueeze(0).float(),size=(256,256),mode='nearest')
print(interpolated_img.shape)



torch.Size([1, 1, 256, 256])


## Numel
returns the total number of elements in the input tensor

In [2]:
import torch
a = torch.zeros(4,4)
print(torch.numel(a))

b=torch.randn(1,2,3,4,5)
print(torch.numel(b))

16
120


## Get the any random sample from Dataloader

In [ ]:
dataset=dataloader.dataset

random_index=int(np.random.random()*len(dataset))
single_example=dataset[random_index]

## ToTransform
Convert PIL Image or ndarray to tensor and scale them 
Detail: Converts PIL image or numpy.ndarray(H,W,C) in range [0,255] to a torch.FloatTensor of shape (C,H,W) in the range [0.0,1.0] 