# Convolution

In [15]:
import numpy as np


F = np.array([1, 0, -1])
H = np.array([3, 1, 4, 1, 5, 9])

con1 = np.convolve(H, F, mode='valid') #here first the value of the filter will be reversed and then applied

#valid: Only where the filter fully overlaps with the signal, resulting in a shorter output.
# full: Convolution computed at every possible position, even at the boundaries, producing a longer output. (like for a filter with size 3 then two 0 are added on both side)
# same: Output is the same size as the input, padding with zeros where necessary.(here just 2 zero will be added at the end for 3 size filter)

print(con1)

con2=np.convolve(F,H,mode='valid')

print(con2) #convlution is commutative so value same

cor1=np.correlate(H,F,mode='valid')

print(cor1)

cor2=np.correlate(F,H,mode='valid')

print(cor2)  #correlation is not commutative




[1 0 1 8]
[1 0 1 8]
[-1  0 -1 -8]
[-8 -1  0 -1]
